### ISSUE TITLE
Can your swerve rotate in the auto

### ISSUE THREAD

**Issue by mendax1234** [strykeforce/infiniterecharge#115]
l notice that your team has done a good job in auto . Notice that you also use swervecontrollercommand , so can your swerve rotate in the path?

**Comment by jhh** [comment]
We saw your posts on Chief Delphi and don't have a lot to add to what already has been posted in response. We haven't had a use-case for rotating in a path since we started using the HolonomicController. If we come up with anything in this season that is relevant and novel, we'll follow up on Chief.
